version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install and configure dependencies
          command: 'sudo npm install -g @quasar/cli@latest && sudo npm install -g gh-pages@latest && git config user.email "ci-build@tobymosque.net" && git config user.name "ci-build"'
      - run:
          name: installing dependencies
          command: 'cd test/app && yarn && quasar upgrade -i'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build test app
          command: 'cd test/app && quasar build -m ssr'
      - run:
          name: Deploy docs to gh-pages branch
          command: 'sudo gh-pages --dotfiles --message "[skip ci] Updates" --branch master --repo https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git --dist test/app/dist/ssr'