version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install and configure dependencies
          command: 'sudo npm install -g @quasar/cli@latest && sudo npm install -g gh-pages@latest && git config user.email "ci-build@tobymosque.net" && git config user.name "ci-build"'
      - run:
          name: installing dependencies
          command: 'cd test/app && yarn && quasar upgrade -i'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "3a:1b:c0:44:cc:96:70:91:fe:a7:de:d9:27:03:48:ef"
      - run:
          name: build test app
          command: 'cd test/app && quasar build -m spa'
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist test/app/dist/spa
