version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge 
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Update quasar-cli
          command: 'sudo npm install -g @quasar/cli@latest'
      - run:
          name: Update test app depedencies
          command: 'cd /test/app && quasar upgrade -i'
      - run:
          name: build test app
          command: 'cd /test/app && quasar build -m spa'
      - run:
          name: moving desployed artifacts to docs folder
          command: 'mv /test/app/dist/app /docs'
